### ISSUE TITLE
autoinstallation via MENU in npp-7.6.2-x86 does not work

### ISSUE THREAD

**Issue by s3n0** [chcg/NPP_HexEdit#12]
Hello, 

autoinstallation via MENU in npp-7.6.2-x86 does not work.

So I had to manually download the ZIP archive with the current plugin version (0.9.5) for NPP x86. Then I created the "NPP\plugins\HexEditor" subfolder and copied the "HexEditor.dll" file from the archive. After restarting NPP everything works.

P.S.: 
In plugin information, it says that the plugin is for NPP 5.4 (see attachment). Is it really dead and the old version of the plugin ?
![npp_5 4_old_version](https://user-images.githubusercontent.com/13181404/53843451-baa2e400-3fa2-11e9-8f05-373d39697e9f.png)

**Comment by chcg** [comment]
@s3n0 Autoinstallation via what menu entry? PluginAdmin? In this case this is a dup to #9 
Hexeditor is not yet part of the plugin list of PluginAdmin at https://github.com/notepad-plus-plus/nppPluginList, mainly due to some open bugs/crashes, see #1 and #11

**Comment by s3n0** [comment]
Yes via MENU - "Plugin Admin". I saw this plugin in the list and wanted to install it (since I saw it there). I checked the HexEditor box in the Plugin Admin. Then I installed the checked plugins and nothing happened. Manual download from the Internet + unpacking to the appropriate folder in Notepad++ has solved my problem. HexEditor works already.

**Comment by chcg** [comment]
Just tested the download via PluginAdmin with N++ 7.6.4 portable without a problem. Also via appveyor the download of each plugin is tested on each list update, see e.g. https://ci.appveyor.com/project/donho/npppluginlist/builds/22913945/job/l5o31lcfr632o4ca. Manually checkin the link with the browser gave me a timeout warning on the first try. After reloading the download was ok again. So maybe at the time of downloading in your case the connection was too slow. Unfortunately the download component of N++ (https://github.com/notepad-plus-plus/wingup) is not presenting an error to the user.

**Comment by chcg** [comment]
Added https://github.com/chcg/NPP_HexEdit/releases/tag/0.9.8 to plugin Admin list for N++ 7.9
