### ISSUE TITLE
Crash when I open .nfo files

### ISSUE THREAD

**Issue by Orriky** [chcg/NPP_HexEdit#13]
Notepad++ crashes when I open .nfo files only when HexEditor is installed

**Comment by chcg** [comment]
@Orriky Which version of N++ and Hexeditor do you use? 32/64 bit?

**Comment by Orriky** [comment]
Hi,

I use 32 bit

**Comment by PeterCodar** [comment]
Same here. As soon as I manually install the 64bit HexEditor Plugin, I can't open NFO files anymore. NP++ crashes.
NP++ version: v7.8.9 64bit
HexEditor version: v0.9.6 64bit from https://github.com/chcg/NPP_HexEdit/releases/tag/0.9.6

If I remove this plugin, NFO's can be opened without any issue.

**Comment by KnIfER** [comment]
So context menu of the explorer will crash npp when hex plugin is installed. 

To debug such issue, just feed the nfo path into VS->debug->command line arguments.

![image (1)](https://user-images.githubusercontent.com/11593903/92404033-3c119e80-f165-11ea-941c-77ac648a806b.jpg)

**Comment by KnIfER** [comment]
But... why does  nfo files cause this nullptr error?
