### ISSUE TITLE
Not Work For npp-7.6.6 x64

### ISSUE THREAD

**Issue by AtomicGu** [chcg/NPP_HexEdit#14]
I copy the dll file to the Plugins folder, but it doesn`t show up in notepad++.
This situation started since i update npp to 7.6.6.
Maybe HexEdit needs an update?

**Comment by chcg** [comment]
See https://notepad-plus-plus.org/community/topic/16645/new-plugins-home-where-notepad-will-load-from and https://notepad-plus-plus.org/features/plugin-admin.html.
You need a subfolder named like the plugin dll under <NPP_INST_DIR>\plugins. So in this case <NPP_INST_DIR>\plugins\HexEditor\HexEditor.dll.
