### ISSUE TITLE
It cannot be install correctly

### ISSUE THREAD

**Issue by Juddd** [chcg/NPP_HexEdit#15]
My Notepad++ is version v7.6.6. This is the position after `HexEditor.dll` unpacked.

 ![](https://i.stack.imgur.com/MZPWT.png)

But as you see, the plugin is not installed successfully...

**Comment by chcg** [comment]
@Juddd See #14 and #12. For 32bit you could use PluginAdmin to download and install Hexeditor. For x64 you still need to do it manually and since N++ 7.6:

> See https://notepad-plus-plus.org/community/topic/16645/new-plugins-home-where-notepad-will-load-from and https://notepad-plus-plus.org/features/plugin-admin.html.
> You need a subfolder named like the plugin dll under <NPP_INST_DIR>\plugins. So in this case <NPP_INST_DIR>\plugins\HexEditor\HexEditor.dll.
