### ISSUE TITLE
A BIG BUG(When file is not too long)

### ISSUE THREAD

**Issue by sky5454** [chcg/NPP_HexEdit#16]
![image](https://user-images.githubusercontent.com/12370628/58529829-f7335400-820e-11e9-9f12-043d264ddd08.png)
When file is not too long, hex display has a bug.
The image show the different between BZ and HexEditor.
And BZ is right. HexEditor has a  bug when file is not too long (such as the file only has 6bits )

**Comment by chcg** [comment]
@sky5454 Which version of HexEditor do you use? Together with which version of N++? 32 or 64bit?

**Comment by chcg** [comment]
Reproduced with N++ 7.7.0 64bit and current Hexedit release. Also the data without Hex View is cutted in this case, see:
![grafik](https://user-images.githubusercontent.com/12630740/58628681-b0129500-82da-11e9-9602-346b7ed6d1f8.png)

**Comment by sky5454** [comment]
Thank You.

**Comment by chcg** [comment]
So this issue depends on a N++ fix, see https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3836.
