### ISSUE TITLE
64 bit version is not working correctly..........

### ISSUE THREAD

**Issue by Suleman-Elahi** [chcg/NPP_HexEdit#2]
The 64 bit version of the plugin doesn't seem to work properly........ It throws an address violation exception as soon as you try to edit any value. And as a result NPP crashes and exists without saving anything.....

**Comment by chcg** [comment]
@Suleman-Elahi  Which version are you using? 0.9.5.11? Which OS and N++ version?

**Comment by a161803398** [comment]
I also encounter same problem on Notepad++ v7.5.4 (64-bit) in Windows 10 Pro(Build 1709)
with the latest 64x release (0.9.5.11).

I also try the test build 0.9.5.13 artifacts, still got same error.
![errormsg](https://user-images.githubusercontent.com/7911601/35895924-96c4a966-0bf4-11e8-83d0-224c4e78cdf2.PNG)


The attach is the dump file.
[NppDump.zip](https://github.com/chcg/NPP_HexEdit/files/1701552/NppDump.zip)

Hope this can help you fix the bug. Thank you !

**Comment by Suleman-Elahi** [comment]
Hi gain, 

I was trying to use the HexEditor_0.9.5.11_x64.zip (latest release) on Windows 10 64 bit OS, build 17083.
The version of the notepad was also the latest. However, after that I installed the 32 bit version of the plugin in 32 bit version of Notepad++ and guess what it worked like charm.......

**Comment by chcg** [comment]
@Suleman-Elahi See https://github.com/chcg/NPP_HexEdit/releases/tag/0.9.5.19, seems to be running without coredumps.

**Comment by a161803398** [comment]
@chcg I have tested 0.9.5.19 x64 version on 64-bit Notepad++, and it works without any problem.

Thank you very much.
