### ISSUE TITLE
Paste Crash

### ISSUE THREAD

**Issue by JanisPlayer** [chcg/NPP_HexEdit#20]
Paste this hex code in the blue area and its crash.
https://pastebin.com/adChvzpE

![Crash](https://user-images.githubusercontent.com/54918417/68716318-3c242a80-05a4-11ea-87ad-ec7acc6a9975.PNG)
Debugger:
![Crash2](https://user-images.githubusercontent.com/54918417/68716335-42b2a200-05a4-11ea-8f9a-77123291770e.PNG)
![Crash3](https://user-images.githubusercontent.com/54918417/68716338-4514fc00-05a4-11ea-8f40-85df7c82a254.PNG)
Video:
https://youtu.be/N0hu251pFZA

**Comment by chcg** [comment]
Images could be directly uploaded also here at github
![zab7e42x](https://user-images.githubusercontent.com/12630740/68714317-f4030900-059f-11ea-91de-a8b769922c92.png)

**Comment by JanisPlayer** [comment]
Thank you, I have searched the function.  xD

**Comment by chcg** [comment]
@JanisPlayer Which version of the hexEditor plugin do you use and which version of N++ in 32 or 64bit? (Could you add the Debug info of N++ please)

**Comment by JanisPlayer** [comment]
Plugin "HEX-Editor" Version: 0.9.5
Notepad++ Debug Info:
Notepad++` v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : D:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by chcg** [comment]
Data from pastebin:

`55 31 D2 89 E5 8B 45 08 56 8B 75 0C 53 8D 58 FF 0F B6 0C 16 88 4C 13 01 83 C2 01 84 C9 75 F1 5B 5E 5D C3`

**Comment by KnIfER** [comment]
@JanisPlayer  How did you copy?

**Comment by KnIfER** [comment]
![20200916_213634_GifNo 0](https://user-images.githubusercontent.com/11593903/93345608-9990a400-f865-11ea-883e-1c28b4fdcf0a.gif)

[new 1.txt](https://github.com/chcg/NPP_HexEdit/files/5232523/new.1.txt)
