### ISSUE TITLE
Not compatible with recent versions of Npp

### ISSUE THREAD

**Issue by mohabouz** [chcg/NPP_HexEdit#21]
it says that it "Cannot load 32-bit plugin." even if it's 64-bit version.
and it continues : "HexEditor.dll is not compatible with the current version of Notepad++."

![image](https://user-images.githubusercontent.com/6238319/68894156-fb085380-0726-11ea-8dc6-5c622a3a7413.png)

**Comment by chcg** [comment]
@mohabouz 
64bit version of N++ needs the 64bit version of the plugin, e.g. https://github.com/chcg/NPP_HexEdit/releases/download/0.9.5.19/HexEditor_0.9.5.19_x64.zip
32bit version of N++ needs the 32bit version of the plugin, e.g. https://github.com/chcg/NPP_HexEdit/releases/download/0.9.5.19/HexEditor_0.9.5.19_x86.zip

The error popup is created by N++ and can't be influenced by the plugin itself. So I think this is not the right project to correct the popup text or state more clearly the actual problem.

**Comment by mohabouz** [comment]
I really don't understand what you said in the last part of your comment, nevertheless, it's not that I don't know what's what i.e 32bit or/and 63bit version of the plugin, all what I'm going to say is, go ahead, download the latest version of Npp and test it out and look for yourself, other than that, I think it is a compatibility issue.
