### ISSUE TITLE
Activate View in HEX should switch between original/plugin Go to window.

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [chcg/NPP_HexEdit#29]
When we have open original `Go to`  window, then running `View in HEX` should switch this window to `Go to` window created by plugin, and vice versa (when we turn off `View in HEX`). Now we can have open both windows in standard or hex view, which is wrong, because one of them doesn't work well anyway. It should be the same behavior as for `Find` and `Replace` windows.

**Comment by chcg** [comment]
Confirmed.
