### ISSUE TITLE
Release build has doubled in size

### ISSUE THREAD

**Issue by Gitoffthelawn** [chcg/NPP_HexEdit#32]
Thank you for continuing this useful plugin.

I noticed that the 32-bit release build of the DLL is twice the size of that offered on https://sourceforge.net/projects/npp-plugins/files/Hex Editor/Hex Editor Plugin v0.9.5/

Why is this?  Is this an issue?

Also, the version number within the build has not been updated at all, resulting in some confusion.  Is it okay to update it within the DLL to reflect the version number in this repo?

**Comment by chcg** [comment]
Probably the usage of MS Visual Studio to build the plugin with MS CRT which is quite huge, but that is no real problem.

See https://github.com/chcg/NPP_HexEdit/commit/b3a21013d0c97cb3062c9264064e0854ea8fb4df for the preparation of a 0.9.6 release.

**Comment by Gitoffthelawn** [comment]
@chcg 
Thanks.  I do wonder, however, if that is all that is causing it.  It's almost *exactly* twice the size.  Maybe just a weird coincidence, but maybe not?

Note that with multiple plugins added to Notepad++, initial load time increases as well as memory use.  Overall, I think it's best to optimize plugin size and efficiency as much as possible.

Thanks!
