### ISSUE TITLE
Update infos in help... command.

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [chcg/NPP_HexEdit#38]
@chcg  Would be nice to have correct infos, at least for reporting bugs :)
![a](https://user-images.githubusercontent.com/2730894/93910540-836d6280-fd01-11ea-980e-b0e30c016425.gif)

**Comment by chcg** [comment]
Fixed with https://github.com/chcg/NPP_HexEdit/releases/tag/0.9.8
