### ISSUE TITLE
An exception occurred due to plugin: HexEditor.dll Exception reason: Access violation

### ISSUE THREAD

**Issue by trivalik** [chcg/NPP_HexEdit#43]
Since version 7.9 of Notepad++ during startup the error: "An exception occurred due to plugin: HexEditor.dll Exception reason: Access violation" appears every time.

Here sounds like solved, https://github.com/JetNpp/HexEditor, but not how, just recompile?

**Comment by cmeriaux** [comment]
See #36

**Comment by trivalik** [comment]
Thanks that solved it.
