### ISSUE TITLE
Access violation in latest version of NPP

### ISSUE THREAD

**Issue by alex7071** [chcg/NPP_HexEdit#44]
After updating NPP, trying to view file in hex editor results in Access violation.

![image](https://user-images.githubusercontent.com/23233542/96687070-0bd63600-1388-11eb-8451-87ca751e26f6.png)

Latest NPP version (just updated) OS: Windows 10

![image](https://user-images.githubusercontent.com/23233542/96687161-2c9e8b80-1388-11eb-98a8-7eb7e72e4b67.png)

**Comment by smrky1** [comment]
Update to v0.9.8, that fixes the problem: https://github.com/chcg/NPP_HexEdit/releases

**Comment by alex7071** [comment]
Will do, thanks. Didn't see the issue was fixed, since it was closed. Next time I should look at the closed issues as well.

**Comment by chcg** [comment]
Fixed by PR #36
