### ISSUE TITLE
Blurry text rendering

### ISSUE THREAD

**Issue by aslze** [chcg/NPP_HexEdit#45]
I posted this same issue on this other repository, thinking that it was the *official* HexEdit plugin:

https://github.com/JetNpp/HexEditor/issues/3

Text in the HexEdit plugin had looked blurry for years. And they quickly fixed the issue. I tried their newly built plugin and text now looks crisp. But that does not seem to be the *official* repo, that which then populates N++ Plugin Manager (in fact it has no code, just binaries). Is this repo *the one*?

**Comment by chcg** [comment]
@aslze Yes, the current version at PA (https://github.com/notepad-plus-plus/nppPluginList) is taken from this repo. It would be nice to take over the modification done at https://github.com/JetNpp/HexEditor/issues/3.
@JetMeta Are you willing to provide your fix for this repo? As PR?

**Comment by JetMeta** [comment]
@chcg, @aslze 
Hi Guys, I have made a pr [Fix: Fonts are now drawn in default mode](https://github.com/chcg/NPP_HexEdit/pull/46/commits/d6250182c83471d5204b45da34941a727c8ce018). Hope this will help.

According to [Qs on CLEARTYPE_QUALITY][1] and [CreateFontA function][2], I restored drawn method to default mode, so font display will depend on settings of the os . 

[1]:https://microsoft.public.win32.programmer.gdi.narkive.com/aN0sKX1g/qs-on-cleartype-quality
[2]:https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createfonta

**Comment by chcg** [comment]
Fix from PR #46 merged.
