### ISSUE TITLE
binary copy paste

### ISSUE THREAD

**Issue by chcg** [chcg/NPP_HexEdit#5]
@metachuh 
See https://notepad-plus-plus.org/community/topic/14341/plugin-manager-removal-hosting/7

cool, i completely missed out that you had the hexeditor plugin ported to x64.

do you use it yourself enough to tweak it a bit ?
if yes, would it be possible to implement a binary copy paste ?
(like the npp built in edit > paste special > copy/paste binary content, or using the npp built in binary safe copy paste routines)

because the normal hexedit plugin 0.9.5 behaviour, if you copy a hex string like:
aa 00 bb 00 cc 00
would be pasted the scintilla way as:
aa 20 bb 20 cc 20
replacing all nul characters with spaces

greetings, metachuh

**Comment by MetaChuh** [comment]
👍

**Comment by mirh** [comment]
Allegedly fixed in #62

**Comment by chcg** [comment]
Fixed by https://github.com/chcg/NPP_HexEdit/releases/tag/0.9.11
