### ISSUE TITLE
incompatibility with np++ 8.1.5

### ISSUE THREAD

**Issue by BlackMage2** [chcg/NPP_HexEdit#58]
i have installed Notepad++ 8.1.5 win64 and the NPP_HexEdit x64 plugin 0.9.10 is not recognized at all

it isn't in the Plugins list in ? -> Debug Info...

**Comment by chcg** [comment]
@BlackMage2 How did you install the plugin? Via PluginAdmin? I don't have this issue with:

```
Notepad++ v8.1.6   (64-bit)
Build time : Oct 10 2021 - 14:10:29
Path : C:\Users\xyz\npp.8.1.6.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1266
Current ANSI codepage : 1252
Plugins : HexEditor.dll ImgTag.dll mimeTools.dll NppConverter.dll NppExport.dll 
```


Please be aware of the yet unresolved issue https://github.com/chcg/NPP_HexEdit/issues/51.

**Comment by chcg** [comment]
As there were no further complains about the download via PluginAdmin I will close the issue for now.
