### ISSUE TITLE
[Info] Build availability of the latest commit (1st of November)

### ISSUE THREAD

**Issue by pidgeon777** [chcg/NPP_HexEdit#60]
I noticed a new commit:

https://github.com/chcg/NPP_HexEdit/commit/edf1d755d790b31ffac781493d0001106b8e0b0b

I was wondering if its latest build is available somewhere.

**Comment by Gitoffthelawn** [comment]
Ping

**Comment by chcg** [comment]
The appveyor build is just available for 1 month and then delete automatically.
The artifacts from the GH action are still available at https://github.com/chcg/NPP_HexEdit/actions/runs/1407282660.
