### ISSUE TITLE
Creates empty 'Compare' subfolder even when no compares have been performed

### ISSUE THREAD

**Issue by Gitoffthelawn** [chcg/NPP_HexEdit#63]
I'm not sure if this is a bug or a feature, but HexEdit (v0.9.11) creates an empty `Compare` subfolder in the extension's folder, even when no compare has ever been performed.

Obviously, not a big deal, but could be indicative of a bug or unintended behaviour, so I thought I would take a moment to mention it.

**Comment by chcg** [comment]
See #10, so it is intended behaviour.

**Comment by Gitoffthelawn** [comment]
Thanks.  Would it be reasonable to move the 

```
if (::PathFileExists(configPath) == FALSE) 
```

block into the code section that gets called when a compare is actually performed?

Because user data is written to that folder, it would be better practice to write to `%TEMP%` instead of a subfolder of Notepad++'s executable files.  I can create a separate issue for that, or perhaps #10 could be reopened.
