### ISSUE TITLE
Please add it to the new plugin manager (Plugin Admin)

### ISSUE THREAD

**Issue by itsho** [chcg/NPP_HexEdit#9]
Hi.

I've tested the plugin in Notepad++ v7.6.2 (64 bit) and it works great!.

but in this version I had to manually copy the DLL into the new location:
`%ProgramData%\Notepad++\plugins`

So, can you please upload it to `Plugin Admin` (the new Plugin Manager)
you can read more about it here:
https://notepad-plus-plus.org/features/plugin-admin.html

Thanks in advance!

**Comment by phamuc** [comment]
Hello,
I am using Notepad++ v7.6.2   (64-bit)
I had to copy the DLL into
%ProgramData%\Notepad++\plugins\HexEditor\
for it to work.
Just copying the DLL directly into the plugins directory didn't work for me.
Oh..and thank you for the very useful plugin.

**Comment by ArkadiuszMichalski** [comment]
This was done.

**Comment by chcg** [comment]
Added with https://github.com/notepad-plus-plus/nppPluginList/commit/379b2b8d2e7c1dc5177e3ea6274320e830e38093 available with N++ 7.9
